In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame()

In [3]:
df = pd.read_csv('C:/Users/hp/Downloads/earthquake.csv')

In [4]:
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [7]:
df.head()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.076,-23.557,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.938,126.427,Earthquake,15.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic

In [6]:
df.tail(4)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [8]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.shape

(23412, 21)

In [11]:
df.columns

Index(['Date', 'Time', 'Latitude', 'Longitude', 'Type', 'Depth', 'Depth Error',
       'Depth Seismic Stations', 'Magnitude', 'Magnitude Type',
       'Magnitude Error', 'Magnitude Seismic Stations', 'Azimuthal Gap',
       'Horizontal Distance', 'Horizontal Error', 'Root Mean Square', 'ID',
       'Source', 'Location Source', 'Magnitude Source', 'Status'],
      dtype='object')

In [12]:
df.isnull()

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,False,False,False,False,False,False,True,True,False,False,...,True,True,True,True,True,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,...,True,True,True,True,True,False,False,False,False,False
2,False,False,False,False,False,False,True,True,False,False,...,True,True,True,True,True,False,False,False,False,False
3,False,False,False,False,False,False,True,True,False,False,...,True,True,True,True,True,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,...,True,True,True,True,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
23408,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
23409,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
23410,False,False,False,False,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,False,False
23411,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [14]:
df.Date

0        01/02/1965
1        01/04/1965
2        01/05/1965
3        01/08/1965
4        01/09/1965
            ...
23407    12/28/2016
23408    12/28/2016
23409    12/28/2016
23410    12/29/2016
23411    12/30/2016
Name: Date, Length: 23412, dtype: object

In [15]:
# Alternate syntax
df['Date']

0        01/02/1965
1        01/04/1965
2        01/05/1965
3        01/08/1965
4        01/09/1965
            ...
23407    12/28/2016
23408    12/28/2016
23409    12/28/2016
23410    12/29/2016
23411    12/30/2016
Name: Date, Length: 23412, dtype: object

In [16]:
df['Magnitude Type']

0         MW
1         MW
2         MW
3         MW
4         MW
        ...
23407     ML
23408     ML
23409    MWW
23410    MWW
23411     MB
Name: Magnitude Type, Length: 23412, dtype: object

In [17]:
df[['Latitude','Longitude','Type']]

       Latitude  Longitude        Type
0       19.2460   145.6160  Earthquake
1        1.8630   127.3520  Earthquake
2      -20.5790  -173.9720  Earthquake
3      -59.0760   -23.5570  Earthquake
4       11.9380   126.4270  Earthquake
...         ...        ...         ...
23407   38.3917  -118.8941  Earthquake
23408   38.3777  -118.8957  Earthquake
23409   36.9179   140.4262  Earthquake
23410   -9.0283   118.6639  Earthquake
23411   37.3973   141.4103  Earthquake

[23412 rows x 3 columns]

In [18]:
df[['Latitude','Longitude','Type']].head()

   Latitude  Longitude        Type
0    19.246    145.616  Earthquake
1     1.863    127.352  Earthquake
2   -20.579   -173.972  Earthquake
3   -59.076    -23.557  Earthquake
4    11.938    126.427  Earthquake

In [20]:
# drop or delete a column 
df.drop(columns = 'Magnitude Error')

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [21]:
df

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.2460,145.6160,Earthquake,131.60,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.8630,127.3520,Earthquake,80.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.5790,-173.9720,Earthquake,20.00,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic
3,01/08/1965,18:49:43,-59.0760,-23.5570,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860856,ISCGEM,ISCGEM,ISCGEM,Automatic
4,01/09/1965,13:32:50,11.9380,126.4270,Earthquake,15.00,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860890,ISCGEM,ISCGEM,ISCGEM,Automatic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23407,12/28/2016,08:22:12,38.3917,-118.8941,Earthquake,12.30,1.2,40.0,5.6,ML,...,18.0,42.47,0.120,NaN,0.1898,NN00570710,NN,NN,NN,Reviewed
23408,12/28/2016,09:13:47,38.3777,-118.8957,Earthquake,8.80,2.0,33.0,5.5,ML,...,18.0,48.58,0.129,NaN,0.2187,NN00570744,NN,NN,NN,Reviewed
23409,12/28/2016,12:38:51,36.9179,140.4262,Earthquake,10.00,1.8,NaN,5.9,MWW,...,NaN,91.00,0.992,4.8,1.5200,US10007NAF,US,US,US,Reviewed
23410,12/29/2016,22:30:19,-9.0283,118.6639,Earthquake,79.00,1.8,NaN,6.3,MWW,...,NaN,26.00,3.553,6.0,1.4300,US10007NL0,US,US,US,Reviewed
23411,12/30/2016,20:08:28,37.3973,141.4103,Earthquake,11.94,2.2,NaN,5.5,MB,...,428.0,97.00,0.681,4.5,0.9100,US10007NTD,US,US,US,Reviewed

In [22]:
df.drop(columns = 'Magnitude Error', inplace = True)

In [23]:
del df['Magnitude Seismic Stations']

In [24]:
df.shape

(23412, 19)

In [25]:
df.Depth.max()

700.0

In [26]:
df.Depth.min()

-1.1

In [27]:
df.Depth.mode()

0    10.0
dtype: float64

In [28]:
df.Depth.mode()[0]

10.0

In [29]:
df.Depth.std()

122.65189771616214

In [30]:
df.Status.unique()

array(['Automatic', 'Reviewed'], dtype=object)

In [31]:
# nuinque gives count of unique values
df.Status.nunique()

2

In [32]:
df.Type.unique()

array(['Earthquake', 'Nuclear Explosion', 'Explosion', 'Rock Burst'],
      dtype=object)

In [33]:
df.Type.nunique()

4

In [34]:
df.describe()

,Latitude,Longitude,Depth,Depth Error,Depth Seismic Stations,Magnitude,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square
count,23412.000000,23412.000000,23412.000000,4461.000000,7097.000000,23412.000000,7299.000000,1604.000000,1156.000000,17352.000000
mean,1.679033,39.639961,70.767911,4.993115,275.364098,5.882531,44.163532,3.992660,7.662759,1.022784
std,30.113183,125.511959,122.651898,4.875184,162.141631,0.423066,32.141486,5.377262,10.430396,0.188545
min,-77.080000,-179.997000,-1.100000,0.000000,0.000000,5.500000,0.000000,0.004505,0.085000,0.000000
25%,-18.653000,-76.349750,14.522500,1.800000,146.000000,5.600000,24.100000,0.968750,5.300000,0.900000
50%,-3.568500,103.982000,33.000000,3.500000,255.000000,5.700000,36.000000,2.319500,6.700000,1.000000
75%,26.190750,145.026250,54.000000,6.300000,384.000000,6.000000,54.000000,4.724500,8.100000,1.130000
max,86.005000,179.998000,700.000000,91.295000,934.000000,9.100000,360.000000,37.874000,99.000000,3.440000

In [35]:
df[['Latitude','Longitude']]

       Latitude  Longitude
0       19.2460   145.6160
1        1.8630   127.3520
2      -20.5790  -173.9720
3      -59.0760   -23.5570
4       11.9380   126.4270
...         ...        ...
23407   38.3917  -118.8941
23408   38.3777  -118.8957
23409   36.9179   140.4262
23410   -9.0283   118.6639
23411   37.3973   141.4103

[23412 rows x 2 columns]

In [36]:
df.Latitude.min()

-77.08

In [37]:
df[['Latitude','Longitude']].sort_values(by='Latitude')

       Latitude  Longitude
21304   -77.080   -148.864
11457   -72.448    174.838
18716   -67.034    111.199
4237    -66.448    -82.584
5717    -65.721   -175.714
...         ...        ...
14288    85.686     86.034
14255    85.734     84.439
14294    85.735     84.906
2910     85.992     30.825
15812    86.005     31.595

[23412 rows x 2 columns]

In [38]:
df[['Latitude','Longitude']].sort_values(by='Latitude', ascending = False)

       Latitude  Longitude
15812    86.005     31.595
2910     85.992     30.825
14294    85.735     84.906
14255    85.734     84.439
14288    85.686     86.034
...         ...        ...
5717    -65.721   -175.714
4237    -66.448    -82.584
18716   -67.034    111.199
11457   -72.448    174.838
21304   -77.080   -148.864

[23412 rows x 2 columns]

In [40]:
df.Type.nunique()

4

In [42]:
df.Type.value_counts()

Earthquake           23232
Nuclear Explosion      175
Explosion                4
Rock Burst               1
Name: Type, dtype: int64

In [43]:
# Alternate 
df['Type'].value_counts()

Earthquake           23232
Nuclear Explosion      175
Explosion                4
Rock Burst               1
Name: Type, dtype: int64

In [44]:
# Filtering the dataframe

df[df['Type'] == 'Nuclear Explosion']

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
565,12/20/1966,15:30:01,37.302167,-116.408333,Nuclear Explosion,1.2,31.61,16.0,5.62,ML,261.0,1.476,99.0,0.86,CI3329931,CI,CI,CI,Reviewed
897,04/26/1968,15:00:02,37.295333,-116.455667,Nuclear Explosion,1.2,31.61,17.0,5.63,ML,261.0,1.438,99.0,1.03,CI3342128,CI,CI,CI,Reviewed
1129,12/19/1968,16:30:01,37.231500,-116.473667,Nuclear Explosion,1.4,31.61,16.0,5.52,ML,257.0,1.415,99.0,1.36,CI3342181,CI,CI,CI,Reviewed
1380,09/16/1969,14:30:01,37.314167,-116.460667,Nuclear Explosion,1.2,31.61,13.0,5.82,ML,268.0,1.437,99.0,0.33,CI3326197,CI,CI,CI,Reviewed
1532,03/26/1970,19:00:01,37.300500,-116.534167,Nuclear Explosion,1.2,31.61,16.0,5.54,ML,260.0,1.377,99.0,0.35,CI3325031,CI,CI,CI,Reviewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11963,06/10/1994,06:25:58,41.527000,88.710000,Nuclear Explosion,0.0,NaN,NaN,5.80,MB,NaN,NaN,NaN,0.90,USP0006E1A,US,US,US,Reviewed
12142,10/07/1994,03:25:58,41.662000,88.753000,Nuclear Explosion,0.0,NaN,NaN,6.00,MB,NaN,NaN,NaN,0.90,USP0006KQC,US,US,US,Reviewed
12450,05/15/1995,04:05:58,41.603000,88.820000,Nuclear Explosion,0.0,NaN,NaN,6.10,MB,NaN,NaN,NaN,1.00,USP0006XCY,US,US,US,Reviewed
12613,08/17/1995,00:59:58,41.559000,88.800000,Nuclear Explosion,0.0,NaN,NaN,6.00,MB,NaN,NaN,NaN,0.90,USP00071XV,US,US,US,Reviewed
13054,06/08/1996,02:55:58,41.657000,88.690000,Nuclear Explosion,0.0,NaN,NaN,5.90,MB,NaN,NaN,NaN,0.90,USP0007J9V,US,US,US,Reviewed

In [48]:
df[df['Type'] == 'Nuclear Explosion'].shape

(175, 19)

In [49]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')]

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
565,12/20/1966,15:30:01,37.302167,-116.408333,Nuclear Explosion,1.2,31.61,16.0,5.62,ML,261.0,1.476,99.0,0.86,CI3329931,CI,CI,CI,Reviewed
897,04/26/1968,15:00:02,37.295333,-116.455667,Nuclear Explosion,1.2,31.61,17.0,5.63,ML,261.0,1.438,99.0,1.03,CI3342128,CI,CI,CI,Reviewed
1129,12/19/1968,16:30:01,37.231500,-116.473667,Nuclear Explosion,1.4,31.61,16.0,5.52,ML,257.0,1.415,99.0,1.36,CI3342181,CI,CI,CI,Reviewed
1380,09/16/1969,14:30:01,37.314167,-116.460667,Nuclear Explosion,1.2,31.61,13.0,5.82,ML,268.0,1.437,99.0,0.33,CI3326197,CI,CI,CI,Reviewed
1532,03/26/1970,19:00:01,37.300500,-116.534167,Nuclear Explosion,1.2,31.61,16.0,5.54,ML,260.0,1.377,99.0,0.35,CI3325031,CI,CI,CI,Reviewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11963,06/10/1994,06:25:58,41.527000,88.710000,Nuclear Explosion,0.0,NaN,NaN,5.80,MB,NaN,NaN,NaN,0.90,USP0006E1A,US,US,US,Reviewed
12142,10/07/1994,03:25:58,41.662000,88.753000,Nuclear Explosion,0.0,NaN,NaN,6.00,MB,NaN,NaN,NaN,0.90,USP0006KQC,US,US,US,Reviewed
12450,05/15/1995,04:05:58,41.603000,88.820000,Nuclear Explosion,0.0,NaN,NaN,6.10,MB,NaN,NaN,NaN,1.00,USP0006XCY,US,US,US,Reviewed
12613,08/17/1995,00:59:58,41.559000,88.800000,Nuclear Explosion,0.0,NaN,NaN,6.00,MB,NaN,NaN,NaN,0.90,USP00071XV,US,US,US,Reviewed
13054,06/08/1996,02:55:58,41.657000,88.690000,Nuclear Explosion,0.0,NaN,NaN,5.90,MB,NaN,NaN,NaN,0.90,USP0007J9V,US,US,US,Reviewed

In [50]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')].shape

(179, 19)

In [51]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')]['Magnitude']

565      5.62
897      5.63
1129     5.52
1380     5.82
1532     5.54
         ...
11963    5.80
12142    6.00
12450    6.10
12613    6.00
13054    5.90
Name: Magnitude, Length: 179, dtype: float64

In [52]:
df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')][df.Magnitude > 6]

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
2797,07/23/1973,01:22:58,49.986,78.853,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00002TP,US,US,US,Reviewed
2859,09/12/1973,06:59:54,73.302,55.161,Nuclear Explosion,0.0,NaN,NaN,6.8,MB,NaN,NaN,NaN,NaN,USP00003DP,US,US,US,Reviewed
2897,10/27/1973,06:59:57,70.779,54.177,Nuclear Explosion,0.0,NaN,NaN,6.9,MB,NaN,NaN,NaN,NaN,USP00003YA,US,US,US,Reviewed
3218,08/29/1974,09:59:55,73.366,55.094,Nuclear Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP00007UG,US,US,US,Reviewed
3286,11/02/1974,04:59:57,70.817,54.063,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP00008N6,US,US,US,Reviewed
3593,08/23/1975,08:59:58,73.369,54.641,Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP0000CJX,US,US,US,Reviewed
3661,10/18/1975,08:59:56,70.843,53.690,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP0000D69,US,US,US,Reviewed
3663,10/21/1975,11:59:57,73.351,55.078,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,NaN,USP0000D7G,US,US,US,Reviewed
5198,06/23/1979,02:56:58,49.918,78.915,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00011G5,US,US,US,Reviewed
5234,08/04/1979,03:56:57,49.901,78.959,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP000127H,US,US,US,Reviewed
5248,08/18/1979,02:51:57,49.971,79.010,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00012GE,US,US,US,Reviewed
5388,12/23/1979,04:56:58,49.964,78.827,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00014NN,US,US,US,Reviewed
5635,09/14/1980,02:42:39,49.976,78.889,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,NaN,USP00019TD,US,US,US,Reviewed
6061,12/27/1981,03:43:14,49.909,78.873,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,1.0,USP0001HPJ,US,US,US,Reviewed
6177,04/25/1982,03:23:05,49.889,78.931,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001KX8,US,US,US,Reviewed
6230,07/04/1982,01:17:14,49.995,78.856,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001N8V,US,US,US,Reviewed
6363,12/05/1982,03:37:13,49.928,78.869,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001R99,US,US,US,Reviewed
6613,06/12/1983,02:36:44,49.906,78.981,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001W19,US,US,US,Reviewed
6774,10/26/1983,01:55:05,49.921,78.907,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001Z9K,US,US,US,Reviewed
7109,07/14/1984,01:09:11,49.891,78.963,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00025QV,US,US,US,Reviewed
7244,10/27/1984,01:50:11,49.949,78.834,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00028J4,US,US,US,Reviewed
7322,12/16/1984,03:55:03,49.957,78.862,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0002A3E,US,US,US,Reviewed
8457,04/03/1987,01:17:08,49.928,78.829,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00033VD,US,US,US,Reviewed
8531,06/05/1987,04:59:58,41.584,88.737,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00035HR,US,US,US,Reviewed
8561,06/20/1987,00:53:05,49.913,78.735,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP00035XC,US,US,US,Reviewed
8795,12/13/1987,03:21:05,49.989,78.844,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003B88,US,US,US,Reviewed
8808,12/27/1987,03:05:05,49.864,78.758,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003BKH,US,US,US,Reviewed
8877,02/13/1988,03:05:06,49.954,78.910,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003CZN,US,US,US,Reviewed
8952,04/03/1988,01:33:06,49.917,78.945,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003EM3,US,US,US,Reviewed
8989,05/04/1988,00:57:07,49.928,78.769,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003FMX,US,US,US,Reviewed
9166,09/14/1988,03:59:57,49.833,78.808,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003KYJ,US,US,US,Reviewed
9327,01/22/1989,03:57:07,49.924,78.831,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003R3E,US,US,US,Reviewed
10126,08/16/1990,04:59:58,41.564,88.770,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP0004DFG,US,US,US,Reviewed
10907,05/21/1992,04:59:58,41.604,88.813,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,0.8,USP00057T0,US,US,US,Reviewed
12450,05/15/1995,04:05:58,41.603,88.820,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,1.0,USP0006XCY,US,US,US,Reviewed

In [53]:
BigEarthquake = df[(df['Type'] == 'Nuclear Explosion') | (df['Type'] == 'Explosion')][df.Magnitude > 6].copy()

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [54]:
BigEarthquake

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
2797,07/23/1973,01:22:58,49.986,78.853,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00002TP,US,US,US,Reviewed
2859,09/12/1973,06:59:54,73.302,55.161,Nuclear Explosion,0.0,NaN,NaN,6.8,MB,NaN,NaN,NaN,NaN,USP00003DP,US,US,US,Reviewed
2897,10/27/1973,06:59:57,70.779,54.177,Nuclear Explosion,0.0,NaN,NaN,6.9,MB,NaN,NaN,NaN,NaN,USP00003YA,US,US,US,Reviewed
3218,08/29/1974,09:59:55,73.366,55.094,Nuclear Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP00007UG,US,US,US,Reviewed
3286,11/02/1974,04:59:57,70.817,54.063,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP00008N6,US,US,US,Reviewed
3593,08/23/1975,08:59:58,73.369,54.641,Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP0000CJX,US,US,US,Reviewed
3661,10/18/1975,08:59:56,70.843,53.690,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP0000D69,US,US,US,Reviewed
3663,10/21/1975,11:59:57,73.351,55.078,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,NaN,USP0000D7G,US,US,US,Reviewed
5198,06/23/1979,02:56:58,49.918,78.915,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00011G5,US,US,US,Reviewed
5234,08/04/1979,03:56:57,49.901,78.959,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP000127H,US,US,US,Reviewed
5248,08/18/1979,02:51:57,49.971,79.010,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00012GE,US,US,US,Reviewed
5388,12/23/1979,04:56:58,49.964,78.827,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00014NN,US,US,US,Reviewed
5635,09/14/1980,02:42:39,49.976,78.889,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,NaN,USP00019TD,US,US,US,Reviewed
6061,12/27/1981,03:43:14,49.909,78.873,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,1.0,USP0001HPJ,US,US,US,Reviewed
6177,04/25/1982,03:23:05,49.889,78.931,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001KX8,US,US,US,Reviewed
6230,07/04/1982,01:17:14,49.995,78.856,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001N8V,US,US,US,Reviewed
6363,12/05/1982,03:37:13,49.928,78.869,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001R99,US,US,US,Reviewed
6613,06/12/1983,02:36:44,49.906,78.981,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001W19,US,US,US,Reviewed
6774,10/26/1983,01:55:05,49.921,78.907,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001Z9K,US,US,US,Reviewed
7109,07/14/1984,01:09:11,49.891,78.963,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00025QV,US,US,US,Reviewed
7244,10/27/1984,01:50:11,49.949,78.834,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00028J4,US,US,US,Reviewed
7322,12/16/1984,03:55:03,49.957,78.862,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0002A3E,US,US,US,Reviewed
8457,04/03/1987,01:17:08,49.928,78.829,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00033VD,US,US,US,Reviewed
8531,06/05/1987,04:59:58,41.584,88.737,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00035HR,US,US,US,Reviewed
8561,06/20/1987,00:53:05,49.913,78.735,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP00035XC,US,US,US,Reviewed
8795,12/13/1987,03:21:05,49.989,78.844,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003B88,US,US,US,Reviewed
8808,12/27/1987,03:05:05,49.864,78.758,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003BKH,US,US,US,Reviewed
8877,02/13/1988,03:05:06,49.954,78.910,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003CZN,US,US,US,Reviewed
8952,04/03/1988,01:33:06,49.917,78.945,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003EM3,US,US,US,Reviewed
8989,05/04/1988,00:57:07,49.928,78.769,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003FMX,US,US,US,Reviewed
9166,09/14/1988,03:59:57,49.833,78.808,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003KYJ,US,US,US,Reviewed
9327,01/22/1989,03:57:07,49.924,78.831,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003R3E,US,US,US,Reviewed
10126,08/16/1990,04:59:58,41.564,88.770,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP0004DFG,US,US,US,Reviewed
10907,05/21/1992,04:59:58,41.604,88.813,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,0.8,USP00057T0,US,US,US,Reviewed
12450,05/15/1995,04:05:58,41.603,88.820,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,1.0,USP0006XCY,US,US,US,Reviewed

In [55]:
BigEarthquake.reset_index(inplace = True)

In [56]:
BigEarthquake

,index,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,2797,07/23/1973,01:22:58,49.986,78.853,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00002TP,US,US,US,Reviewed
1,2859,09/12/1973,06:59:54,73.302,55.161,Nuclear Explosion,0.0,NaN,NaN,6.8,MB,NaN,NaN,NaN,NaN,USP00003DP,US,US,US,Reviewed
2,2897,10/27/1973,06:59:57,70.779,54.177,Nuclear Explosion,0.0,NaN,NaN,6.9,MB,NaN,NaN,NaN,NaN,USP00003YA,US,US,US,Reviewed
3,3218,08/29/1974,09:59:55,73.366,55.094,Nuclear Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP00007UG,US,US,US,Reviewed
4,3286,11/02/1974,04:59:57,70.817,54.063,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP00008N6,US,US,US,Reviewed
5,3593,08/23/1975,08:59:58,73.369,54.641,Explosion,0.0,NaN,NaN,6.4,MB,NaN,NaN,NaN,NaN,USP0000CJX,US,US,US,Reviewed
6,3661,10/18/1975,08:59:56,70.843,53.690,Nuclear Explosion,0.0,NaN,NaN,6.7,MB,NaN,NaN,NaN,NaN,USP0000D69,US,US,US,Reviewed
7,3663,10/21/1975,11:59:57,73.351,55.078,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,NaN,USP0000D7G,US,US,US,Reviewed
8,5198,06/23/1979,02:56:58,49.918,78.915,Nuclear Explosion,0.0,NaN,NaN,6.3,MB,NaN,NaN,NaN,NaN,USP00011G5,US,US,US,Reviewed
9,5234,08/04/1979,03:56:57,49.901,78.959,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP000127H,US,US,US,Reviewed
10,5248,08/18/1979,02:51:57,49.971,79.010,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00012GE,US,US,US,Reviewed
11,5388,12/23/1979,04:56:58,49.964,78.827,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,NaN,USP00014NN,US,US,US,Reviewed
12,5635,09/14/1980,02:42:39,49.976,78.889,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,NaN,USP00019TD,US,US,US,Reviewed
13,6061,12/27/1981,03:43:14,49.909,78.873,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,1.0,USP0001HPJ,US,US,US,Reviewed
14,6177,04/25/1982,03:23:05,49.889,78.931,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001KX8,US,US,US,Reviewed
15,6230,07/04/1982,01:17:14,49.995,78.856,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001N8V,US,US,US,Reviewed
16,6363,12/05/1982,03:37:13,49.928,78.869,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001R99,US,US,US,Reviewed
17,6613,06/12/1983,02:36:44,49.906,78.981,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0001W19,US,US,US,Reviewed
18,6774,10/26/1983,01:55:05,49.921,78.907,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0001Z9K,US,US,US,Reviewed
19,7109,07/14/1984,01:09:11,49.891,78.963,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00025QV,US,US,US,Reviewed
20,7244,10/27/1984,01:50:11,49.949,78.834,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00028J4,US,US,US,Reviewed
21,7322,12/16/1984,03:55:03,49.957,78.862,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0002A3E,US,US,US,Reviewed
22,8457,04/03/1987,01:17:08,49.928,78.829,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00033VD,US,US,US,Reviewed
23,8531,06/05/1987,04:59:58,41.584,88.737,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP00035HR,US,US,US,Reviewed
24,8561,06/20/1987,00:53:05,49.913,78.735,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP00035XC,US,US,US,Reviewed
25,8795,12/13/1987,03:21:05,49.989,78.844,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003B88,US,US,US,Reviewed
26,8808,12/27/1987,03:05:05,49.864,78.758,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003BKH,US,US,US,Reviewed
27,8877,02/13/1988,03:05:06,49.954,78.910,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003CZN,US,US,US,Reviewed
28,8952,04/03/1988,01:33:06,49.917,78.945,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.8,USP0003EM3,US,US,US,Reviewed
29,8989,05/04/1988,00:57:07,49.928,78.769,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003FMX,US,US,US,Reviewed
30,9166,09/14/1988,03:59:57,49.833,78.808,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003KYJ,US,US,US,Reviewed
31,9327,01/22/1989,03:57:07,49.924,78.831,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,0.9,USP0003R3E,US,US,US,Reviewed
32,10126,08/16/1990,04:59:58,41.564,88.770,Nuclear Explosion,0.0,NaN,NaN,6.2,MB,NaN,NaN,NaN,0.9,USP0004DFG,US,US,US,Reviewed
33,10907,05/21/1992,04:59:58,41.604,88.813,Nuclear Explosion,0.0,NaN,NaN,6.5,MB,NaN,NaN,NaN,0.8,USP00057T0,US,US,US,Reviewed
34,12450,05/15/1995,04:05:58,41.603,88.820,Nuclear Explosion,0.0,NaN,NaN,6.1,MB,NaN,NaN,NaN,1.0,USP0006XCY,US,US,US,Reviewed

In [57]:
# Slicing the dataframe

BigEarthquake.iloc[:10,:7]

   index        Date      Time  Latitude  Longitude               Type  Depth
0   2797  07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0
1   2859  09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0
2   2897  10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0
3   3218  08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0
4   3286  11/02/1974  04:59:57    70.817     54.063  Nuclear Explosion    0.0
5   3593  08/23/1975  08:59:58    73.369     54.641          Explosion    0.0
6   3661  10/18/1975  08:59:56    70.843     53.690  Nuclear Explosion    0.0
7   3663  10/21/1975  11:59:57    73.351     55.078  Nuclear Explosion    0.0
8   5198  06/23/1979  02:56:58    49.918     78.915  Nuclear Explosion    0.0
9   5234  08/04/1979  03:56:57    49.901     78.959  Nuclear Explosion    0.0

In [58]:
BigEarthquake.loc[9]

index                                  5234
Date                             08/04/1979
Time                               03:56:57
Latitude                             49.901
Longitude                            78.959
Type                      Nuclear Explosion
Depth                                     0
Depth Error                             NaN
Depth Seismic Stations                  NaN
Magnitude                               6.1
Magnitude Type                           MB
Azimuthal Gap                           NaN
Horizontal Distance                     NaN
Horizontal Error                        NaN
Root Mean Square                        NaN
ID                               USP000127H
Source                                   US
Location Source                          US
Magnitude Source                         US
Status                             Reviewed
Name: 9, dtype: object

In [61]:
BigEarthquake.loc[9,'Type'] = 'Volcanic Eruption'

In [62]:
BigEarthquake.iloc[:10,:7]

   index        Date      Time  Latitude  Longitude               Type  Depth
0   2797  07/23/1973  01:22:58    49.986     78.853  Nuclear Explosion    0.0
1   2859  09/12/1973  06:59:54    73.302     55.161  Nuclear Explosion    0.0
2   2897  10/27/1973  06:59:57    70.779     54.177  Nuclear Explosion    0.0
3   3218  08/29/1974  09:59:55    73.366     55.094  Nuclear Explosion    0.0
4   3286  11/02/1974  04:59:57    70.817     54.063  Nuclear Explosion    0.0
5   3593  08/23/1975  08:59:58    73.369     54.641          Explosion    0.0
6   3661  10/18/1975  08:59:56    70.843     53.690  Nuclear Explosion    0.0
7   3663  10/21/1975  11:59:57    73.351     55.078  Nuclear Explosion    0.0
8   5198  06/23/1979  02:56:58    49.918     78.915  Nuclear Explosion    0.0
9   5234  08/04/1979  03:56:57    49.901     78.959  Volcanic Eruption    0.0

In [64]:
BigEarthquake['New Column'] = BigEarthquake.Latitude + 100

In [66]:
BigEarthquake.loc[[9]]

,index,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,New Column
9,5234,08/04/1979,03:56:57,49.901,78.959,Volcanic Eruption,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,NaN,USP000127H,US,US,US,Reviewed,149.901

In [67]:
BigEarthquake

,index,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,New Column
0,2797,07/23/1973,01:22:58,49.986,78.853,Nuclear Explosion,0.0,NaN,NaN,6.3,...,NaN,NaN,NaN,NaN,USP00002TP,US,US,US,Reviewed,149.986
1,2859,09/12/1973,06:59:54,73.302,55.161,Nuclear Explosion,0.0,NaN,NaN,6.8,...,NaN,NaN,NaN,NaN,USP00003DP,US,US,US,Reviewed,173.302
2,2897,10/27/1973,06:59:57,70.779,54.177,Nuclear Explosion,0.0,NaN,NaN,6.9,...,NaN,NaN,NaN,NaN,USP00003YA,US,US,US,Reviewed,170.779
3,3218,08/29/1974,09:59:55,73.366,55.094,Nuclear Explosion,0.0,NaN,NaN,6.4,...,NaN,NaN,NaN,NaN,USP00007UG,US,US,US,Reviewed,173.366
4,3286,11/02/1974,04:59:57,70.817,54.063,Nuclear Explosion,0.0,NaN,NaN,6.7,...,NaN,NaN,NaN,NaN,USP00008N6,US,US,US,Reviewed,170.817
5,3593,08/23/1975,08:59:58,73.369,54.641,Explosion,0.0,NaN,NaN,6.4,...,NaN,NaN,NaN,NaN,USP0000CJX,US,US,US,Reviewed,173.369
6,3661,10/18/1975,08:59:56,70.843,53.690,Nuclear Explosion,0.0,NaN,NaN,6.7,...,NaN,NaN,NaN,NaN,USP0000D69,US,US,US,Reviewed,170.843
7,3663,10/21/1975,11:59:57,73.351,55.078,Nuclear Explosion,0.0,NaN,NaN,6.5,...,NaN,NaN,NaN,NaN,USP0000D7G,US,US,US,Reviewed,173.351
8,5198,06/23/1979,02:56:58,49.918,78.915,Nuclear Explosion,0.0,NaN,NaN,6.3,...,NaN,NaN,NaN,NaN,USP00011G5,US,US,US,Reviewed,149.918
9,5234,08/04/1979,03:56:57,49.901,78.959,Volcanic Eruption,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,NaN,USP000127H,US,US,US,Reviewed,149.901
10,5248,08/18/1979,02:51:57,49.971,79.010,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,NaN,USP00012GE,US,US,US,Reviewed,149.971
11,5388,12/23/1979,04:56:58,49.964,78.827,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,NaN,USP00014NN,US,US,US,Reviewed,149.964
12,5635,09/14/1980,02:42:39,49.976,78.889,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,NaN,USP00019TD,US,US,US,Reviewed,149.976
13,6061,12/27/1981,03:43:14,49.909,78.873,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,1.0,USP0001HPJ,US,US,US,Reviewed,149.909
14,6177,04/25/1982,03:23:05,49.889,78.931,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0001KX8,US,US,US,Reviewed,149.889
15,6230,07/04/1982,01:17:14,49.995,78.856,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.8,USP0001N8V,US,US,US,Reviewed,149.995
16,6363,12/05/1982,03:37:13,49.928,78.869,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0001R99,US,US,US,Reviewed,149.928
17,6613,06/12/1983,02:36:44,49.906,78.981,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.8,USP0001W19,US,US,US,Reviewed,149.906
18,6774,10/26/1983,01:55:05,49.921,78.907,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0001Z9K,US,US,US,Reviewed,149.921
19,7109,07/14/1984,01:09:11,49.891,78.963,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,0.9,USP00025QV,US,US,US,Reviewed,149.891
20,7244,10/27/1984,01:50:11,49.949,78.834,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,0.9,USP00028J4,US,US,US,Reviewed,149.949
21,7322,12/16/1984,03:55:03,49.957,78.862,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0002A3E,US,US,US,Reviewed,149.957
22,8457,04/03/1987,01:17:08,49.928,78.829,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,0.9,USP00033VD,US,US,US,Reviewed,149.928
23,8531,06/05/1987,04:59:58,41.584,88.737,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,0.9,USP00035HR,US,US,US,Reviewed,141.584
24,8561,06/20/1987,00:53:05,49.913,78.735,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP00035XC,US,US,US,Reviewed,149.913
25,8795,12/13/1987,03:21:05,49.989,78.844,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0003B88,US,US,US,Reviewed,149.989
26,8808,12/27/1987,03:05:05,49.864,78.758,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.8,USP0003BKH,US,US,US,Reviewed,149.864
27,8877,02/13/1988,03:05:06,49.954,78.910,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.8,USP0003CZN,US,US,US,Reviewed,149.954
28,8952,04/03/1988,01:33:06,49.917,78.945,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.8,USP0003EM3,US,US,US,Reviewed,149.917
29,8989,05/04/1988,00:57:07,49.928,78.769,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0003FMX,US,US,US,Reviewed,149.928
30,9166,09/14/1988,03:59:57,49.833,78.808,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0003KYJ,US,US,US,Reviewed,149.833
31,9327,01/22/1989,03:57:07,49.924,78.831,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,0.9,USP0003R3E,US,US,US,Reviewed,149.924
32,10126,08/16/1990,04:59:58,41.564,88.770,Nuclear Explosion,0.0,NaN,NaN,6.2,...,NaN,NaN,NaN,0.9,USP0004DFG,US,US,US,Reviewed,141.564
33,10907,05/21/1992,04:59:58,41.604,88.813,Nuclear Explosion,0.0,NaN,NaN,6.5,...,NaN,NaN,NaN,0.8,USP00057T0,US,US,US,Reviewed,141.604
34,12450,05/15/1995,04:05:58,41.603,88.820,Nuclear Explosion,0.0,NaN,NaN,6.1,...,NaN,NaN,NaN,1.0,USP0006XCY,US,US,US,Reviewed,141.603